# Generated by Django 4.2.7 on 2023-11-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais_origen', models.CharField(max_length=50)),
                ('nodos', models.PositiveIntegerField()),
                ('num_cores', models.PositiveIntegerField()),
                ('num_ram_tb', models.DecimalField(decimal_places=3, max_digits=15)),
                ('almacenamiento_tb', models.DecimalField(decimal_places=3, max_digits=15)),
                ('teraflops', models.DecimalField(decimal_places=3, max_digits=16)),
                ('sistema_operativo', models.CharField(max_length=200)),
            ],
        ),
    ]
