# Generated by Django 4.2.7 on 2023-11-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0002_pais_remove_computadora_pais_origen_computadora_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
